INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('vnxlwl72ff3e', 'The Network Monthly Meeting', 'Itshappeningingrantcounty', 'This is a meeting of professionals in Grant County to discuss current events, share volunteer and business happenings, and network. There is no agenda and no speaker, and meetings will last just one hour. 
', ' The Hostess House, 723 W 4th St, Marion', '2018-02-01', '12:00', '2018-02-01', '13:00', '0', 'Valerie McHarry', 'vmcharry@dwdcpa.com ', '250-230-2013', '', '', '4kexfc3r', 1, '2018-03-05 02:35:09');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('gtds6uje1zzo', 'Let''s Knit & Crochet', 'Itshappeningingrantcounty', 'Meet every Thursday 4 pm to 5:30 pm. Beginners must register at the Marion Public Library Reference Desk. Learn to knit & Crochet. All levels are welcome. 
', ' Marion Public Library, 600 S Washington St, Marion Indiana', '2018-02-01', '16:00', '2018-02-01', '17:30', '0', 'Sue Bratton', 'joshkim12@gmail.com', '668-2900 ext 145', '', '', 'x3a64b10', 1, '2018-03-05 02:56:57');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('eiilwu0pauuh', 'Crafting with Mrs. Clare', 'Marion Library', 'Thursday, February 1st at 6 pm. Mrs. Clare will be showing you how to build a catch all box. Sign Up Required. Must be 18 years or older. ', ' Marion Public Library, 600 S Washington St, Marion Indiana', '2018-02-01', '18:00', '2018-02-01', '20:00', '0', 'Mary Leffler', ' mleffler@marion.lib.in.us ', ' 668-2900 ext 126', 'http://www.marion.lib.in.us/', '', '0iprcn4e', 1, '2018-03-05 04:05:26');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('0qhowfwlu5hw', 'CSA''s Junie B. Jones is Not a Crook', 'Marion Community School of the Arts', 'CSA''s Theatre company presents Junie B. Jones is Not a Crook', 'Marion High School F. Ritchie Walton PAC 750 W 26th St Marion, IN 46953 ', '2018-02-02', '19:00', '2018-02-02', '21:00', '0', 'CSA', 'info@csa-marion.com', '', '', '', 'x2raiu8r', 1, '2018-03-05 04:09:49');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('q32s2mxpcp6x', 'Take Your Child to the Library Day', 'Marion Public Library', 'Bring your child to the library for story time, craft time, STEAM station experiments and to check out books. All day from 9am till 5pm. ', 'Marion Public Library, 600 S Washington, Marion Indiana', '2018-02-03', '09:00', '2018-02-03', '17:00', '0', 'Tylanna Jones', ' tjones@marion.lib.in.us', '668-2900 ext 109', 'http://www.marion.lib.in.us/', '', 'cr40sep7', 1, '2018-03-05 04:16:14');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('xdu4hm115yiy', 'Children''s Movie "Igor"', 'Marion Library', 'Children''s movie at 1:30 pm on Saturday, February 3rd, free popcorn and soda. Movie is rated PG ', 'Marion Public Library, 600 S Washington, Marion Indiana ', '2018-02-03', '13:30', '2018-02-03', '15:30', '0', 'Mary Leffler', 'mleffler@marion.lib.in.us ', '668-2900 ext 126', 'http://www.marion.lib.in.us/', '', 'd8ez1t4b', 1, '2018-03-05 04:23:10');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('7nzmps2js8ym', 'Marion Board of Works Meeting', 'Council Chambers of City Hall', 'Regular Meeting 
Membership required: No', '301 S. Branson St., Marion, IN 46952', '2018-02-05', '10:00', '2018-02-05', '11:00', '0', 'Aisha Richard', 'ajrichard@cityofmarion.in.gov', '', 'http://www.cityofmarion.in.gov/?q=node/598 ', '', '3i8x6cdl', 1, '2018-03-05 04:28:06');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('hoyc3hyzdu0a', 'Preschool Tales', 'Marion ', 'Preschool Tales,  storytime for children ages 3-6 years. 

', ' Marion Public Library, 600 S Washington St, Marion Indiana', '2018-02-05', '10:30', '2018-02-05', '11:30', '0', 'Tylanna Jones', 'tjones@marion.lib.in.us ', '668-2900 ext 105', '', '', 'qhevvjso', 1, '2018-03-05 05:03:39');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('na99oyyl9j1o', 'Marion Parks & Recreation Board Mtg', 'City Hall', 'Monthly board meeting.  Open to the public. Membership required? No.', '2nd Floor Conference Room of City Hall (301 S. Branson St., Marion IN)', '2018-02-05', '12:00', '2018-02-05', '13:00', '0', 'Rose Cadena', 'rcadena@marionindiana.us', '', '', '', 'pztunzu9', 1, '2018-03-05 05:09:41');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('a3n9jym8dm43', 'Toastmasters', 'YMCA', 'We provide a supportive and positive learning experience in which members are empowered to develop communication and leadership skills, resulting in self-confidence and personal growth', ' YMCA, 123 Sutter Way, Marion, IN 46952, USA', '2018-02-05', '18:30', '2018-02-05', '19:30', '0', 'na', 'na@na.com', '', '', '', 'bbq90mhu', 1, '2018-03-05 05:14:45');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('ahzgyrj7guku', 'Sensory Tales', 'Marion Public Library', 'Activities using blocks, painting and play dough. For children ages 3-6 years. 
Membership required: No ', ' Marion Public Library, 600 S Washington St, Marion Indiana', '2018-02-06', '10:30', '2018-02-06', '11:30', '0', 'Tylanna Jones', 'tjones@marion.lib.in.us ', '668-2900 ext 105', '', '', 's3g1auts', 1, '2018-03-05 05:36:05');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('810x4aw3wuoo', 'Voter Registration', 'Marion Library', '
The Circulation Desk of the Marion Public Library will be doing Voter Registration through the month of March 2018. Please call the Circulation Desk at 668-2900 for further details ', ' Marion Public Library, 600 S Washington, Marion Indiana', '2018-03-01', '09:00', '2018-03-01', '20:00', '0', 'Michelle Morgan', 'mmorgan@marion.lib.in.us ', '668-2900 ext 101 or ext 109', '', '', '3m1isbn4', 1, '2018-03-05 05:37:59');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('95nugch2pbff', 'The Network Monthly Meeting', 'The Hostess House', '
This is a meeting of professionals in Grant County to discuss current events, share volunteer and business happenings, and network. There is no agenda and no speaker, and meetings will last just one hour. 

Cost: Cost of Lunch', ' The Hostess House, 723 W 4th St, Marion', '2018-03-01', '12:00', '2018-03-01', '13:00', '0', 'Valerie McHarry', 'vmcharry@dwdcpa.com ', '', '', '', '1943z968', 1, '2018-03-05 05:39:16');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('d1av1rtealxt', 'Let''s Knit & Crochet', 'Marion Public Library', 'Meet every Thursday 4 pm to 5:30 pm. Beginners must register at the Marion Public Library Reference Desk. Learn to knit & Crochet. All levels are welcome. 


Membership required: No 
Cost: Fee for beginners is $15 to cover the cost of materials. ', 'Marion Public Library, 600 S Washington St, Marion Indiana', '2018-03-01', '16:00', '2018-03-01', '17:30', '0', ' Sue Bratton', 'sbratton@marion.lib.in.us ', ' 668-2900 ext 145', '', '', 'v330llnh', 1, '2018-03-05 05:44:58');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('958vaed1jgla', 'THE LAND (gallery show and panel discussion)', 'Indiana Wesleyan University', 'Reception and panel discussion for a gallery show of paintings, sculpture, photographs, and writing that explore themes from imaging of the landscape to human interaction with the environment.


The show features works by Dr. Katie Karnehm-Esh, John Rhett, Nick Roudebush, Kyle Ragsdale, and Tom Hansell 
', 'Beard Arts Center, Indiana Wesleyan University', '2018-03-01', '18:00', '2018-03-01', '20:00', '0', 'Henrik Soderstrom', 'henrik.soderstrom@indwes.edu ', '585-739-4886', '', '', 'rtxsidga', 1, '2018-03-05 06:09:36');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('q77mtd2t819i', 'Crafting with Clare', 'Marion Public Library', 'Thursday, March 1st @ 6pm. Must be 18 years or older and sign up required. Clare will be teaching you how to make wooden birthday calendar.', 'Marion Public Library, 1963, 600 S Washington St, Marion, IN 46953, USA', '2018-03-01', '18:00', '2018-03-01', '19:00', '0', 'Mary Leffler', 'mleffler@marion.lib.in.us', '668-2900 ext 130', '', '', 'aqjval6g', 1, '2018-03-05 06:19:39');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('4dfoy4a3cpjm', 'Voter Registration', 'Marion Public Library', 'The Circulation Desk of the Marion Public Library will be doing Voter Registration through the month of March 2018. Please call the Circulation Desk at 668-2900 for further details ', ' Marion Public Library, 600 S Washington, Marion Indiana', '2018-03-02', '09:00', '2018-03-02', '20:00', '0', 'Michelle Morgan', 'mmorgan@marion.lib.in.us', '668-2900 ext 101 or ext 109', '', 'yoxk6fa3q7mx.jpg', 'osob1w4h', 1, '2018-03-05 06:21:46');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('qibv6aue49tu', 'Happy Birthday, Dr. Seuss', 'Marion Public Library', 'Thursday, March 2nd @ 4:30 pm. Children preschool to 6th grade. Registration required. Join us for crafts, snacks, stories and games.', ' Marion Public Library, 1963, 600 S Washington St, Marion, IN 46953, USA', '2018-03-02', '16:30', '2018-03-02', '17:30', '0', 'Tylanna Jones', 'tjones@marion.lib.in.us', '668-2900 ext 109', '', '', 'de4sjihu', 1, '2018-03-05 06:24:34');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('hg4opqg0lsb1', 'Voter Registration', 'Marion Public Library', 'The Circulation Desk of the Marion Public Library will be doing Voter Registration through the month of March 2018. Please call the Circulation Desk at 668-2900 for further details ', ' Marion Public Library, 600 S Washington, Marion Indiana', '2018-03-03', '09:00', '2018-03-03', '20:00', '0', 'Michelle Morgan', 'mmorgan@marion.lib.in.us ', '668-2900 ext 101 or ext 109', '', 'n7ugfk16pwnr.jpg', '0s4frqzb', 1, '2018-03-05 06:35:57');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('st160p6djdk3', 'Marion Civic Theatre''s Adult Theatre classes', 'Marion Civic Theatre', '
Marion Civic Theatre is offering a 6-week theatre and acting class. Adult theatre classes will meet every Saturday from 12:00 PM to 3:00 PM at the James Dean Memorial Theatre starting February 17 and ending March 24. Classes are taught by Andrew Daniels. 

What to bring: Wear comfortable clothes that you can move in (black sweat pants and black T-shirt are preferred), Water bottle, Notebook & pen or pencil 
', '509 S Washington St, Marion, IN 46953', '2018-03-03', '12:00', '2018-03-03', '15:00', '0', 'Tabetha Nice', ' marioncivictheatre@att.net ', '765-668-7800', 'https://www.marion-civic-theatre.org/happening-at-mct/adult-theatre-classes/ ', '', '8qs7yyzt', 1, '2018-03-05 06:37:29');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('ek5a5z66mxot', 'Saturday Movie', 'Marion Public Library', ' If you like funny monster movies, join us on Saturday, March 3rd @ 1:30 pm for a movie rated PG. Meeting Room B.', 'Marion Public Library, 1963, 600 S Washington St, Marion, IN 46953, USA', '2018-03-03', '13:30', '2018-03-03', '15:30', '0', 'Mary Leffler', 'mleffler@marion.lib.in.us', '668-2900 ext 130', '', '', 'z03yrzq1', 1, '2018-03-05 06:39:03');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('ywqilqs285yk', 'Voter Registration', 'Marion Public Library', 'The Circulation Desk of the Marion Public Library will be doing Voter Registration through the month of March 2018. Please call the Circulation Desk at 668-2900 for further details ', ' Marion Public Library, 600 S Washington, Marion Indiana', '2018-03-04', '09:00', '2018-03-04', '20:00', '0', ' Michelle Morgan', 'mmorgan@marion.lib.in.us ', '668-2900 ext 101 or ext 109', '', 'h3zgarn06blr.jpg', 'vl2xkthu', 1, '2018-03-05 06:46:22');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('sw519qstadal', 'Voter Registration', 'Marion Public Library', '
The Circulation Desk of the Marion Public Library will be doing Voter Registration through the month of March 2018. Please call the Circulation Desk at 668-2900 for further details ', ' Marion Public Library, 600 S Washington, Marion Indiana (', '2018-03-05', '09:00', '2018-03-05', '20:00', '0', 'Michelle Morgan', 'mmorgan@marion.lib.in.us ', '668-2900 ext 101 or ext 109', '', '', '4ayvh055', 1, '2018-03-05 06:54:01');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('oat16w8hdim9', 'Marion Board of Works Meeting', 'City of Marion', 'Regular Meeting', ' Council Chambers of City Hall (301 S. Branson St., Marion, IN 46952)', '2018-03-05', '10:00', '2018-03-05', '11:00', '0', 'Aisha Richard', 'ajrichard@cityofmarion.in.gov', '', 'http://www.cityofmarion.in.gov/?q=node/598 ', '', 'hjac4vwz', 1, '2018-03-05 06:59:07');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('z39yd4jtx5bv', 'Preschool Tales', 'Marion Public Library', 'Preschool Tales, storytime for children ages 3-6 years.', 'Marion Public Library, 600 S Washington St, Marion Indiana', '2018-03-05', '10:30', '2018-03-05', '11:30', '0', 'Tylanna Jones', 'tjones@marion.lib.in.us ', '668-2900 ext 105', '', '', 'i5v0lgpn', 1, '2018-03-05 07:03:04');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('v3m0wsgtxfsi', 'Marion Parks & Recreation Board Mtg', 'Marion Indiana', 'Monthly Board Meeting,
Open to the public
No membership required', ' 2nd Floor Conference Room of City Hall (301 S. Branson St., Marion IN)', '2018-03-05', '12:00', '2018-03-05', '13:00', '0', 'Rose Cadena', 'rcadena@marionindiana.us', '', '', '', 'r3ezkheh', 1, '2018-03-05 07:04:21');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('2w0e0pd7mltm', 'Marion/McCulloch Junior High joint Band Concert', 'Marion High and McCulloch Junior high School', 'Come out and hear the award-winning musicians from Marion High School and McCulloch Junior High School share some special music.  

Membership required: No 
Cost: free 
', ' Walton Center @ Marion High School, 750 W. 26th St., Marion', '2018-03-05', '18:00', '2018-03-05', '20:00', '0', 'Patricia Gibson', 'pgibson@marion.k12.in.us ', '765-662-2546', '', '', 'xk2sqhiw', 1, '2018-03-05 09:50:18');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('rmpwlvmj92q3', 'Toastmasters', 'YMCA', 'We provide a supportive and positive learning experience in which members are empowered to develop communication and leadership skills, resulting in self-confidence and personal growth', ' YMCA, 123 Sutter Way, Marion, IN 46952, USA', '2018-03-05', '18:30', '2018-03-05', '19:30', '0', 'YMCA', 'YMCA@YMCA.com', '', '', '', 'annnwp3y', 1, '2018-03-05 09:51:36');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('gh62hvz247v1', 'Voter Registration', 'Marion Public Library', 'The Circulation Desk of the Marion Public Library will be doing Voter Registration through the month of March 2018. Please call the Circulation Desk at 668-2900 for further details 

Membership required: No 
Cost: free ', 'Marion Public Library, 600 S Washington, Marion Indiana ', '2018-03-06', '09:00', '2018-03-06', '20:00', '0', 'Michelle Morgan', 'mmorgan@marion.lib.in.us ', '668-2900 ext 101 or ext 109', '', '', 'z06z030k', 1, '2018-03-05 09:52:46');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('ueghk4vhcb4y', 'Sensory Tales', 'Marion Public Library', '
Activities using blocks, painting and play dough. For children ages 3-6 years. 

Membership required: No 
Cost: free ', 'Marion Public Library, 600 S Washington St, Marion Indiana', '2018-03-06', '22:30', '2018-03-06', '11:30', '0', 'Tylanna Jones', 'tjones@marion.lib.in.us ', ' 668-2900 ext 105', '', '', '854z39g5', 1, '2018-03-05 09:55:25');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('elgaa9wbjtaz', 'Alcohol Tobacco Commission Meeting', 'Charlie Wallace', '
Regularly scheduled meeting ', '1st Flr of County Council Mtg Rm, Grant County Complex (401 S. Adams St., Marion, IN) ', '2018-03-06', '11:00', '2018-03-06', '12:00', '0', 'Charlie Wallace', 'cmlw1947@gmail.com ', '', '', '', 'uctp63fy', 1, '2018-03-05 10:02:08');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('elln45z0l12j', 'Marion City Council Meeting', 'Council Chamber of City Hall', 'Regular Meeting', ' Council Chambers of City Hall (301 S. Branson St., Marion, IN 46952)', '2018-03-06', '19:00', '2018-03-06', '20:00', '0', 'Debbie Goodman', 'dgoodman@cityofmarion.in.gov', '', 'www.cityofmarion.in.gov/?q=node/575', '', 'xyeu4vx8', 1, '2018-03-05 10:03:30');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('26b1v2zw2gtb', 'BYOC', 'Grant County Economic Growth Council', 'This is a networking event open to anyone in Grant County!', 'Abbey Coffee, 1500 S Western Ave. Marion IN', '2018-03-07', '07:00', '2018-03-07', '09:00', '0', 'Victoria Herring', 'vherring@grantcounty.com ', '', 'https://www.facebook.com/groups/293750314441997/ ', '0u529xor4yo5.png', 'liuu1cx6', 1, '2018-03-05 10:05:00');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('5j43us8mz7wh', 'Voter Registration', 'Marion Public Library', 'The Circulation Desk of the Marion Public Library will be doing Voter Registration through the month of March 2018. Please call the Circulation Desk at 668-2900 for further details ', 'Marion Public Library, 600 S Washington, Marion Indiana', '2018-03-07', '09:00', '2018-03-07', '20:00', '0', 'Michelle Morgan', 'mmorgan@marion.lib.in.us ', '668-2900 ext 101 or ext 109', '', 'g1jpw30qv8kb.jpg', 'bzr03nlu', 1, '2018-03-05 10:08:06');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('ivck0armvgyx', ' Prevent Child Abuse 2018 Training and Luncheon ', 'Grant County Prevent Child Abuse ', 'Prevent Child Abuse (PCA) Grant County Council‘s 2018 Training and Luncheon. 
Topic: "Juvenile Suicide Awareness and Prevention". Keynote speaker: David Berman, Director of Development at Mental Health America Indiana. The training is provided at no cost to attendees. 
Luncheon catered by the Giant Bistro. Sign up early!  Register before March 23rd for $20. Thereafter, attendees will be charged $25.  The FINAL REGISTRATION DEADLINE is Friday, April 6th.     
', '261 S Commerce Dr. Marion, IN 46953', '2018-04-11', '08:00', '2018-04-11', '13:00', '0', 'Jessy Pearson-Cheney ', 'grantcountypca@gmail.com', '', 'https://goo.gl/forms/dLfZcBP3tgwX6X323', '0w2f7x0fv49y.png', '96xbjlum', 1, '2018-03-05 16:57:02');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('tp0alfzxvujg', 'Digital Media Day - Sales & Marketing Seminar', 'Marion-Grant County Chamber of Commerce', 'Digital Media Day', '261 S Commerce Drive', '2018-04-12', '08:00', '2018-04-12', '14:30', '$ 50.00', 'Kylie Jackson', 'kylie@marionchamber.org', '7656645107', 'http://www.marionchamber.org/pages/sales--marketing-seminar', '0a6zl5dnaq6q.png', '38ibv4be', 1, '2018-03-05 19:41:08');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('fljjv6oidmkb', 'Art, Journaling & Beyond', 'Marion Public Library', 'Learn how to be creative & create a journal with art, goals, gratitude, etc.', '600 S. Washington St., Marion, IN, 46953', '2018-03-21', '17:00', '2018-03-21', '18:00', '$ 5.00', 'Mary Leffler', 'mleffler@marion.lib.in.us', '668-2900 ext 126', 'http://www.marion.lib.in.us/', '', 'cxfpzmr1', 1, '2018-03-06 20:57:30');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('bamodduyc5br', 'Teen Gaming', 'Marion Public Library', 'Open to teens grades 7 to 12. Join us for an afternoon of video and board games.', '600 S. Washington St., Marion, IN, 46953', '2018-03-24', '14:30', '2018-03-24', '15:30', '0', 'Kristen Gioe', 'kgioe@marion.lib.in.us', '668-2900 ext 108', 'http://www.marion.lib.in.us/', '', 'asm4flti', 1, '2018-03-06 21:18:30');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('xo7p3pztmnx6', 'Spring Break Movie', 'Marion Public Library', 'Family movie rated PG, free popcorn and soda', '600 S. Washington St., Marion, IN, 46953', '2018-03-27', '13:00', '2018-03-27', '15:00', '0', 'Tylanna Jones', 'tjones@marion.lib.in.us', '668-2900 ext 109', 'http://www.marion.lib.in.us/', '', 'q0o9uq2q', 1, '2018-03-06 21:24:32');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('7oq3x4epyfro', 'Teen Movie', 'Marion Public Library', 'Movie for teens grades 7-12. Movie rated PG-13. Free pop and popcorn.', '600 S. Washington St., Marion, IN, 46953', '2018-03-28', '13:00', '2018-03-28', '03:00', '0', 'Kristen Gioe', 'kgioe@marion.lib.in.us', '668-2900 ext 108', 'http://www.marion.lib.in.us/', '', '09it561w', 1, '2018-03-06 21:29:12');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('2j69t2fgvqok', 'Good Friday Service', 'College Wesleyan Church', 'We invite you and your community to join us for our Good Friday service at 12:00pm in the sanctuary. In this service, we will experience songs and scripture that focus on Jesus as the "Bread of Life." Amidst the terrible suffering of the cross, God was in control. He is offering us life even through death. ', '200 E 38th St. Marion, IN 46953', '2018-03-30', '12:00', '2018-03-30', '13:00', '0', 'Jordan Rife', 'jordan.rife@collegewes.com', '5633405552', 'https://www.collegewes.com/', '', '5rw74d6o', 1, '2018-03-06 21:35:48');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('rn93ylxok9je', 'A Night at Carey', 'Carey Services', 'The second annual A Night at Carey event is approaching. As part of National Disability Awareness Month, Carey Services is sponsoring an evening of food and recognition with an Irish theme.

The highlight of the evening will be The Carey Awards, four awards that will honor involvement with improving the lives of people with disabilities.', 'Roseburg Event Center, 2983 W 38th St, Marion, IN 46953', '2018-03-17', '18:00', '2018-03-17', '20:30', '$ 75.00', 'Greg Maynard', 'GMaynard@careyservices.com', '7656688961', 'www.careyservices.com/anightatcarey', '', 'pm4jbrfs', 1, '2018-03-07 14:16:56');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('b5chcgvgykoc', 'Earth Day', 'Parks Department, Marion Utilities', 'You''re invited to the 5th Anniversary of Marion''s Annual Earth Day Celebration! There will be plenty of fun things going on that will display, promote, and celebrate the Earth and doing our part as stewards of the environment!

 Kids’ Activities • Green Exhibits • Eco-friendly Vendors • Food to Purchase • Receive a FREE TREE & Compost!

Workshop Schedule:
- 4:30 pm - Learn how to plant a Tree!
- 5:30 pm - Learn about the Wastewater Treatment Process!

 Come & go as you please!', 'The Garden House at Matter Park', '2018-04-20', '16:00', '2018-04-20', '19:00', '0', 'Brittany Riner', 'briner@marionutilities.com', '765-664-2391', 'http://bit.ly/2HsQEqT', 'cy9dajs1882s.jpg', 'wr2rbzij', 1, '2018-03-12 19:40:51');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('8zjpavz59ekh', 'Community Day Obstacle Course & Fishing', 'Marion Utilities', 'Join us for our 4th Annual Community Day to help low-income families in Marion! Community Day is an awesome event for families with a NEW, fun obstacle course and free fishing at Matter Park! For a small fee, you and your family can traverse our NEW, one-of-a-kind obstacle course that includes a rope swing, tire run, zip line, water canon, and much more! Take advantage of the free activities including fishing at the Matter Park Pond, picnic, and prizes and give-aways! 

 All proceeds go to benefitting H2O Community - a program created by Marion Utilities to help Marion''s low-income families with financial assistance on their utility bill, as well as financial education.', 'Matter Park, Marion, IN', '2018-06-09', '09:00', '2018-06-09', '13:00', 'Varies', 'Brittany Riner', 'briner@marionutilities.com', '765-664-2391', 'https://www.eventbrite.com/e/community-day-obstacle-course-fishing-tickets-43629202118', 'va7lmvaobjhh.jpg', '6ek7tcro', 1, '2018-03-12 19:44:57');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('0rfpwkdxgiht', 'Bunny Breakfast', 'Marion High School Band Boosters', 'The Marion Band Boosters will host the Bunny Breakfast from 7:30 to 11:30 a.m., in conjunction with the Million Egg Hunt set that morning at MHS''s Dick Lootens Stadium (starts at 10 a.m.).

The Bunny Breakfast will be inside MHS''s Bill Green Arena. (Enter at Door 14, near the stadium, or Door 11, near the tennis courts.) There will be special appearances by the Easter Bunny!

Breakfast includes pancakes, sausage, milk and juice.

Tickets:
~ $5 adult (3 pancakes, 3 sausages, 1 milk, 1 juice)
~ $3 children ages 3 to 10 (2 pancakes, 2 sausages, 1 milk, 1 juice)
~ free for children 2 and younger. (1 pancake, 1 sausage, 1 milk, 1 juice)

Tickets are sold at the door. Proceeds benefit the growing, award-winning MHS band program!

Thank you to our sponsor, IHOP!', 'Bill Green Arena at Marion High School (enter Door 11 or 14)', '2018-03-31', '07:30', '2018-03-31', '11:30', 'Tickets sold at the door', 'Patricia Gibson', 'pgibson@marion.k12.in.us', '765-662-2546', 'http://mhs.marion.k12.in.us/index.cfm?event=news&pageid=1476', '8do7ddyosndb.jpg', 'qdbh9jka', 1, '2018-03-14 14:33:05');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('bu7vq05b59do', 'Little Giants Preschool 2018-19 - Kendall ', 'Little Giants Preschool / Marion Community Schools', 'Little Giants Preschool encompasses Marion Community Schools'' Head Start-, Title I- and On My Way Pre-K-funded programs, along with our special needs preschool program. Students must be 3 years old by Aug. 1, 2018, and must live in Grant County. 

(Please note that application DOES NOT guarantee enrollment. We have limited spots available and will follow up with families regarding enrollment status of their child. Waiting lists will be implemented when necessary.)

Required documentation:

~ Verification of income (such as  2016 tax form, W-2 form, check stubs, child support receipts, social security payment information, unemployment verification, TANF case worker statement, etc. Please bring in 12 months of income verification.)
~ Proof of residence (such as a recent utility bill) if available
~ Child’s birth certificate
~ Child’s immunization records
~ Child’s Medicaid card or private insurance card
~ Child’s Social Security card or number', 'Kendall Elementary, 2009 W. Kem Road', '2018-04-04', '07:45', '2018-04-04', '15:00', '', 'Deb Hendricks', 'dhendricks@marion.k12.in.us', '765-651-2080', 'http://mecc.marion.k12.in.us/index.cfm?newsid=4360&pagetype=509&dir=3', '', 'tsll28no', 1, '2018-03-14 14:47:12');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('1phlnycms29y', 'Little Giants Preschool 2018-19 - Riverview ', 'Little Giants Preschool / Marion Community Schools', 'Little Giants Preschool encompasses Marion Community Schools'' Head Start-, Title I- and On My Way Pre-K-funded programs, along with our special needs preschool program. Students must be 3 years old by Aug. 1, 2018 and must live in Grant County. 

(Please note that application DOES NOT guarantee enrollment. We have limited spots available and will follow up with families regarding enrollment status of their child. Waiting lists will be implemented when necessary.)

Required documentation:

~ Verification of income (2016 tax form, W-2 form, check stubs, child support receipts, social security payment information, unemployment verification, TANF case worker statement, etc. Please bring in 12 months of income verification.)
~ Proof of residence (such as a recent utility bill) if available
~ Child’s birth certificate
~ Child’s immunization records
~ Child’s Medicaid card or private insurance card', 'Riverview Elementary, 513 W. Buckingham Dr', '2018-04-02', '07:45', '2018-04-02', '15:00', '', 'Deb Hendricks', 'dhendricks@marion.k12.in.us', '765-651-2080', 'http://mecc.marion.k12.in.us/index.cfm?newsid=4360&pagetype=509&dir=3', 'tsm4b0ef5d0i.JPG', 'thiyd65k', 1, '2018-03-14 14:51:48');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('p3ec5ctbmsvk', 'Little Giants Preschool 2018-19 - Frances Slocum', 'Little Giants Preschool / Marion Community Schools', 'Little Giants Preschool encompasses Marion Community Schools'' Head Start-, Title I- and On My Way Pre-K-funded programs, along with our special needs preschool program. Students must be 3 years old by Aug. 1, 2018 and must live in Grant County. 

(Please note that application DOES NOT guarantee enrollment. We have limited spots available and will follow up with families regarding enrollment status of their child. Waiting lists will be implemented when necessary.)

Required documentation:

~ Verification of income (2016 tax form, W-2 form, check stubs, child support receipts, social security payment information, unemployment verification, TANF case worker statement, etc. Please bring in 12 months of income verification.)
~ Proof of residence (such as a recent utility bill) if available
~ Child’s birth certificate
~ Child’s immunization records
~ Child’s Medicaid card or private insurance card', 'Frances Slocum Elementary, 2909 S. Torrence St', '2018-04-03', '07:45', '2018-04-03', '15:00', '', 'Deb Hendricks', 'dhendricks@marion.k12.in.us', '765-651-2080', 'http://mecc.marion.k12.in.us/index.cfm?newsid=4360&pagetype=509&dir=3', 'fiyv4nqwwpbs.JPG', '4x4vat0v', 1, '2018-03-14 14:53:31');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('f5lj2lgz50n6', 'Little Giants Preschool 2018-19 - Allan ', 'Little Giants Preschool / Marion Community Schools', 'Little Giants Preschool encompasses Marion Community Schools'' Head Start-, Title I- and On My Way Pre-K-funded programs, along with our special needs preschool program. Students must be 3 years old by Aug. 1, 2018 and must live in Grant County. 

(Please note that application DOES NOT guarantee enrollment. We have limited spots available and will follow up with families regarding enrollment status of their child. Waiting lists will be implemented when necessary.)

Required documentation:

~ Verification of income (2016 tax form, W-2 form, check stubs, child support receipts, social security payment information, unemployment verification, TANF case worker statement, etc. Please bring in 12 months of income verification.)
~ Proof of residence (such as a recent utility bill) if available
~ Child’s birth certificate
~ Child’s immunization records
~ Child’s Medicaid card or private insurance card
~ Child’s Social Security card or number
', 'Allen Elementary, 1115 E. Bradford St', '2018-04-05', '07:45', '2018-04-05', '15:00', '', 'Deb Hendricks', 'dhendricks@marion.k12.in.us', '765-651-2080', 'http://mecc.marion.k12.in.us/index.cfm?newsid=4360&pagetype=509&dir=3', 'omcitgtpxel9.JPG', 't4072ii6', 1, '2018-03-14 14:55:14');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('eo0wgdkr8lnl', 'MHS Bands - ISSMA Preview / Spring Concert', 'Marion High School', 'Come out for the end-of-the-year concert and hear what our talented young musicians have prepared for their Indiana State School Music Association competitions!', 'Walton Performing Arts Center at Marion High School, 750 W. 26th St., Marion', '2018-04-16', '19:30', '2018-04-16', '21:30', '', 'Josh Huff', 'jhuff@marion.k12.in.us', '765-664-9051', '', 'ofidnufunmd1.png', 'lmx7c0ac', 1, '2018-03-14 15:06:48');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('r8w3fkzdgn8s', 'MCS All-City Art Show', 'Marion Community Schools', 'Come out and enjoy lots of art on display from our talented students from all grades, plus interactive activities and musical performances!

The art show will run from 11 a.m. to 8 p.m. May 18 and 11 a.m. to 5 p.m. May 19. ', 'Walton Performing Arts Center at Marion High School, 750 W. 26th St., Marion', '2018-05-18', '11:00', '2018-05-18', '20:00', '', 'Nate Larson', 'nlarson@marion.k12.in.us', '765-664-9051', '', 'plqm9awwwlek.jpg', '8ceq6pk3', 1, '2018-03-14 15:11:13');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('hhwob12swsah', 'MCS All-City Art Show', 'Marion Community Schools', 'Come out and enjoy lots of art on display from our talented students from all grades, plus interactive activities and musical performances!

The art show will run from 11 a.m. to 8 p.m. May 18 and 11 a.m. to 5 p.m. May 19. ', 'Walton Performing Arts Center at Marion High School, 750 W. 26th St., Marion', '2018-05-19', '11:00', '2018-05-19', '17:00', '', 'Nate Larson', 'nlarson@marion.k12.in.us', '765-664-9051', 'http://www.marion.k12.in.us/index.cfm?event=show&singleevent=7135', '7x3puijxqono.jpg', '78t6qocz', 1, '2018-03-14 15:15:20');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('b8k17gnrpbws', 'Essential Oils Class', 'Marion Public Library', 'April 2, 2018 @ 6 pm. Discover the Power of Essential Oils. Class presented by Sandy Wilson.', 'Marion Public Library, 600 S Washington, Marion Indiana', '2018-04-02', '18:00', '2018-04-02', '20:00', '', 'Mary Leffler', 'mleffler@marion.lib.in.us', '668-2900 ext 130', '', '', 'uihzzvcm', 1, '2018-03-14 15:21:46');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('qrhafvpcvv10', 'Friends Book Sale', 'Marion Public Library', 'The Marion Public Library Friends Group will be holding their annual book sale on Friday- April 6th from 5-8 pm, Saturday-April 7th from 9am-5pm & Sunday-April 8th from 1-4 pm', 'Marion Public Library, 600 S Washington, Marion Indiana', '2018-04-06', '17:00', '2018-04-06', '20:00', '', 'Mary Eckerle', 'meckerle@marion.lib.in.us', '765-668-2900', '', '', 'xwsljoao', 1, '2018-03-14 15:26:10');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('qharjovh3z9w', 'Friends Book Sale', 'Marion Public Library', 'The Marion Public Library Friends Group will be holding their annual book sale on Friday- April 6th from 5-8 pm, Saturday-April 7th from 9am-5pm & Sunday-April 8th from 1-4 pm', 'Marion Public Library, 600 S Washington, Marion Indiana', '2018-04-07', '09:00', '2018-04-07', '17:00', '', 'Mary Eckerle', 'meckerle@marion.lib.in.us', '765-668-2900', '', '', '3qwz9f3i', 1, '2018-03-14 15:27:43');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('jeztup3oxbyg', 'Kent Anderson Butler Gallery show', 'Division of Art+Design, IWU', 'On Friday, March 23rd from 6-8pm, the Williams Gallery in the Beard Arts Center at Indiana Wesleyan University will host a gallery show of new work by Kent Anderson Butler titled Searching, But No One Is Listening. ', 'Beard Arts Center (campus of IWU- 4201 South Washington Street, Marion, IN 46953)', '2018-03-23', '18:00', '2018-03-23', '20:00', 'Free', 'Henrik Soderstrom', 'henrik.soderstrom@indwes.edu', '', 'https://www.facebook.com/events/590066831345171/?notif_t=plan_user_joined&notif_id=1520894802531348', '', '4uk363gi', 1, '2018-03-14 15:43:48');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('c9kykzng86n8', ' 20th Annual Cruisin'' To Care', 'Gilead Ministries', 'Car show', '1129 N Baldwin Ave, Marion, IN 46952', '2018-05-19', '09:00', '2018-05-19', '15:00', '13', 'Bill Sparks', 'bills@gileadministries.com', '', 'https://www.facebook.com/events/191409444784055/', '', 'zpcga8jr', 1, '2018-03-14 15:48:56');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('whdcnrwaohrf', 'sd', 'sd', 'sd', 'sd', '2018-03-18', '09:00', '2018-03-17', '10:00', '', 'sd', 'sd@sdc.com', '', '', '', 's6lmru6v', 0, '2018-03-18 23:26:07');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('y3l8xuh7mspy', 'Children Party', 'Taylor Uni', 'Children party for uplanders', 'Wengatz', '2018-03-18', '09:00', '2018-03-19', '10:00', '1', 'Maxwell Partnal', 'maxwell_partnal@taylor.edu', '7659120125', 'taylor.edu', '', 'rq0bsk07', 0, '2018-03-18 23:27:30');
INSERT INTO event (id, title, organization, description, location, start_date, start_time, end_date, end_time, cost, contact_name, contact_email, contact_phone, url, photo, password, verified, created_at) VALUES ('4gk7zvnyv5l6', 'Test 1', 'Test 2', 'Xd', 'Xx', '2018-03-18', '09:00', '2018-03-18', '10:00', '', 'Xx', 'xx@z.com', '', '', '', 'geizz6wm', 0, '2018-03-18 23:32:06');